config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "top#index"
  
  get 'about', to: "top#about"
  
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  
  get "signup", to: "users#new"
  resources :users, only: [:show, :create, :edit, :update, :destroy] do
    member do 
      get :followings 
      get :followers 
      get :likes
      
    end 
  end 
  
  resources :posts do
    member do 
      get :followings
    end 
  end 
  
  resources :relationships, only: [:create, :destroy]
  
  resources :favorites, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/map.rb
class Map < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  validates :name, presence:true
  belongs_to :user
  has_many :reverses_of_favorite, class_name:"Favorite", dependent: :destroy
  has_many :like_users, through: :reverses_of_favorite, source: :user, dependent: :destroy
  mount_uploader :image, ImageUploader #写真投稿用
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :name, presence: true
  validates :city, presence: true
  validates :password_digest, presence: true
  validates :email, uniqueness: { case_sensitive: false }
  
  has_many :posts, dependent: :destroy
  
  has_many :relationships, dependent: :destroy
  has_many :followings, through: :relationships, source: :follow, dependent: :destroy
  has_many :reverses_of_relationship, class_name: "Relationship", foreign_key: "follow_id", dependent: :destroy
  has_many :followers, through: :reverses_of_relationship, source: :user, dependent: :destroy
  
  has_many :favorites, dependent: :destroy
  has_many :like_posts, through: :favorites, source: :post, dependent: :destroy
  
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end 
  end 
  
  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end
  
  def following?(other_user)
    self.followings.include?(other_user)
  end 
  
  def feed_posts
    Post.where(user_id: self.following_ids)
  end 
  
  def favorite(post)
    self.favorites.find_or_create_by(post_id: post.id)
  end 
  
  def unfavorite(post)
    favorite = self.favorites.find_by(post_id: post.id)
    favorite.destroy if favorite 
  end 
  
  def favorite?(post)
    self.like_posts.include?(post)
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  include Pagy::Backend
  
  def require_user_logged_in
      unless logged_in?
          redirect_to root_url
      end 
  end 
  
  def require_current_user
    unless current_user
      redirect_to root_url
    end 
  end
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    current_user.favorite(post)
    flash[:success] = "Favorite success"
    redirect_to post_url(post)
  end

  def destroy
    post = Post.find(params[:post_id])
    current_user.unfavorite(post)
    flash[:success] = "Unfavorite success"
    redirect_to post_url(post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :require_user_logged_in, only: [:new]
  
  def index
    @posts = Post.all
  end
  
  def show
    @post = Post.find(params[:id])
  end
  
  def new
    @post = current_user.posts.build
  end 

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "Post success"
      redirect_to user_url(current_user)
    else 
      flash.now[:danger] = "Post lose"
      render :new
    end
  end
  
  def update
    if @post.update(post_params)
      flash[:success] = "Post success"
      redirect_to user_url(current_user)
    else 
      flash.now[:danger] = "Post lose"
      render :edit
    end
  end

  
  def destroy
    @post.destroy
    flash[:success] = "Delete success"
    redirect_to root_url
  end


  def followings
    @user = current_user
    @pagy,@posts = pagy(current_user.feed_posts.order(id: :desc))
  end   
  
  
  private
    def post_params
      params.require(:post).permit(:name, :genre, :comment, :station, :image, :image_cache)
    end
    
    def correct_user
      @post = current_user.posts.find_by(id: params[:id])
      unless @post 
        redirect_to root_url
      end 
    end 
    

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :require_user_logged_in
  
  def create
    user = User.find(params[:follow_id])
    current_user.follow(user)
    flash[:success] = "Follow success"
    redirect_to user
  end

  def destroy
    user = User.find(params[:follow_id])
    current_user.unfollow(user)
    flash[:success] = "Unfollow success"
    redirect_to user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email,password)
      flash[:success] = "Login success"
      redirect_to followings_post_url(@user)
    else 
      flash.now[:danger] = "Login lose"
      render :new 
    end 
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "Logout success"
    redirect_to root_url
  end
  
private
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      #ログイン成功
      session[:user_id] = @user.id
      return true
    else
      #ログイン失敗
      return false
    end
  end
  
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    def index
        @pagy, @posts = pagy (Post.all)
    end 
    
    def about
    end 
    

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :followings, :followers, :likes]
  before_action :correct_user, only:[:edit, :update]
  
  def show
    @pagy, @posts = pagy(@user.posts)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Signup success"
      redirect_to root_url
    else 
      flash.now[:danger] = "signup lose"
      render :new
    end 
  end
  
  def edit 
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Update success"
      redirect_to user_url(@user)
    else 
      flash.now[:danger] = "Update lose"
      render :edit
    end
  end
  
  
  def destroy
    
  end
  
  def followings
    @user = current_user
    @pagy, @followings = pagy(@user.followings)
  end

  def followers
    @pagy, @followers = pagy(@user.followers)
  end
  
  def likes 
    @pagy, @posts = pagy(@user.like_posts)
  end
  
private
  def user_params
    params.require(:user).permit(:name, :email,:password, :password_confirmation, :birthday, :city)
  end 
  
  def set_user
    @user = User.find(params[:id])
  end 
  
  def correct_user
   @user = User.find(params[:id])
   redirect_to root_url unless @user == current_user
  end 
  
end

app/helpers/application_helper.rb
module ApplicationHelper
    include SessionsHelper
    include UsersHelper
    
    include Pagy::Frontend
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end 
  
  def logged_in?
    !!current_user 
  end 
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    end
end

app/views/favorites/_favorite_button.html.erb
<% if current_user.favorite?(post) %>
  <%= form_with(model: current_user.favorites.find_by(post_id: post.id), method: :delete) do |f| %>
    <%= hidden_field_tag :post_id, post.id %>
    <%= button_tag type: "submit", class: "btn btn-danger btn-sm" do %>
      <i class="fas fa-heart-circle"></i>
    <% end %>
  <% end %>
<% else %>
  <%= form_with(model: current_user.favorites.build) do |f| %>
    <%= hidden_field_tag :post_id, post.id %>
    <%= button_tag type: "submit", class: "btn btn-light btn-sm" do %>
      <i class="fas fa-heart-circle"></i>
    <% end %>
  <% end %>
<% end %> 

app/views/posts/_follow_button.html.erb
<% unless current_user == user %>
  <% if current_user.following?(user) %>
    <%= form_with(model: current_user.relationships.find_by(follow_id: user.id), method: :delete) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit "Unfollow", class: "btn btn-danger w-100" %>
    <% end %>
  <% else %>
    <%= form_with(model: current_user.relationships.build) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit "Follow", class: "btn btn-primary w-100" %>
    <% end %>
  <% end %>
<% end %>

app/views/posts/_index.html.erb
<% if @posts.any? %>
  <div class="row row-eq-height g-2 mb-4">
    <% @posts.each do |post| %>
    <div class="col-md-4">
      <div class="card bg-light bg-gradient h-100">
        <div class="card-img-top text-center">
          <% if post.image? %>
            <%= image_tag post.image.url, width: "50%", height: "100%" %>
          <% end %>
        </div>
        <div class="card-body border-top">
          <div class="row">
            <div class="col-sm-4 border-end">
              <p class="card-text pt-3">Name: <%= link_to post.user.name, user_path(post.user), class: "text-decoration-none" %></p>
              <% if post.user.birthday? %>
                <p class="card-text">Age:<%= (DateTime.now.to_i - post.user.birthday.to_i)  / (86400* 365) %>
                </p>
              <% else %>
                <p class="card-text">Age: None</p>
              <% end %>
              
              <p class="card-text">City: <%= post.user.city %></p>
            </div>
            
            <div class="col-sm-8">
              <p class="card-text pt-3">Name of place：<%= link_to post.name, post_path(post), class:"text-muted" %></p>
              <p class="card-text">Genre： <%= post.genre %></p>
              <p class="card-text">Station： <%= post.station %></p>
              <p class="card-text">Comment: <%= safe_join(post.comment.split("\n"),tag(:br)) %></p>
              
              <% if logged_in? %> 
                <div class="ms-4 text-center">
                 <%= render "favorites/favorite_button", post: post %>
                </div>
                
                <div class="text-end pt-2">
                  <% if current_user == post.user %>
                    <%= link_to "Edit", edit_post_path(post), class:"btn btn-outline-warning" %>
                    <%= link_to "Delete", post, method: :delete, data: {confirm: "You sure?"}, class:"btn btn-outline-danger" %>
                  <% end %>
                </div>
              <% end %>
            </div>
            
          
          </div>
          
         
        </div>
      </div>

    </div>
    <% end %>
  </div>
  <%== pagy_bootstrap_nav(@pagy) %>
<% end %>

app/views/posts/edit.html.erb
<div class="mt-3">
  <div class="text-center">
    <h1>Edit post</h1>
  </div>
  
  <div class="row pb-3">
    <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @post) do |f| %>
        <%= render "layouts/error_message", model: f.object %>
      
      <div class="mb-3">
        <%= f.label :name, "Name of place" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= f.label :genre, "Genre" %>
        <%= f.select :genre, options_for_select([['Japanese', "Japanese"], ['Chinese', "Chinese"], ['Korean', "Korean"], ['American', "American"], ['Italian', "Italian"], ['French', "French"], ['Others', "Others"]]), class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= f.label :station, "Station" %>
        <%= f.text_field :station, class: "form-control" %>
      </div>
      <div class="mb-3">
        <% if @post.image? %>
          <%= image_tag @post.image.url, width: '80%', height: '80%' %>
        <% end %>
        <div class="mb-3">
          <%= f.label :image, "Image" %>
          <%= f.file_field :image %>
          <%= f.hidden_field :image_cache %>
        </div>
      </div>
      <div class="mb-3">
        <%= f.label :comment, "Comment" %>
        <%= f.text_area :comment, class: "form-control" %>
      </div>
  
      <%= f.submit "Post", class:"btn btn-primary w-100" %>
    <% end %>
    </div>
  </div>
</div>

app/views/posts/followings.html.erb
<div>
  <h2 class="text-center">Profile</h2>
  <div class="row">
    <div class="card col-sm-5 text-center mx-auto">
      <div class="card-header">
        <h2><%= @user.name %></h2>
      </div>
      <div class="card-body">
        <div class="row">
          <div class="col-sm-3">
            <img class="rounded me-2 mb-5 mt-4 " src="<%= gravatar_url(@user, {size: 100}) %>" alt="">
          </div>
          <div class="col-sm-9 mt-4">
            <% if @user.birthday? %>
              <p class="card-text">Age:<%= (DateTime.now.to_i - @user.birthday.to_i)  / (86400* 365) %>
              </p>
            <% else %>
              <p class="card-text">Age: None</p>
            <% end %>
            <p class="card-text">City:<%= @user.city %></p>
            <% if current_user == @user %>
              <%= link_to "Edit", edit_user_path(@user), class: 'btn btn-outline-warning' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>



<div class="mt-3">
  <h2 class="text-center">POSTS OF FOLLOWINGS</h2>
  <%= render "posts/index" %>
</div>

app/views/posts/new.html.erb
<div class="mt-3">
  <div class="text-center">
    <h1>New post</h1>
  </div>
  
  <div class="row pb-3">
    <div class="col-sm-6 offset-sm-3">
  
      <%= form_with(model: @post) do |f| %>
      <%= render "layouts/error_message", model: f.object %>
        
        <div class="mb-3">
          <%= f.label :name, "Name of place" %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :genre, "Genre" %>
          <%= f.select :genre, options_for_select([['Japanese', "Japanese"], ['Chinese', "Chinese"], ['Korean', "Korean"], ['American', "American"], ['Italian', "Italian"], ['French', "French"], ['Others', "Others"]]), class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :station, "Station" %>
          <%= f.text_field :station, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :image, "Image" %>
          <%= f.file_field :image %>
          <%= f.hidden_field :image_cache %>
        </div>
        <div class="mb-3">
          <%= f.label :comment, "Comment" %>
          <%= f.text_area :comment, class: "form-control" %>
        </div>
    
        <%= f.submit "Post", class:"btn btn-primary w-100" %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div>
  <h2 class="mt-2 text-center">Post</h2>
  <div class="row">
    <div class="card col-sm-5 offset-col-3 mx-auto">
      <div class="card-img-top text-center">
        <% if @post.image? %>
          <%= image_tag @post.image.url, width: '100%', height: '100%' %>
        <% end %>
      </div>
      <div class="card-body border-top">
        <p class="card-text">Name of place：<%= link_to @post.name, post_path(@post), class:"text-muted" %></p>
        <p class="card-text">Genre：<%= @post.genre %></p>
        <p class="card-text">Station：<%= @post.station %></p>
        <p class="card-text">Created.at：<%= @post.created_at.to_s(:datetime_jp) %></p>
        <p class="card-text">Comment:<%= safe_join(@post.comment.split("\n"),tag(:br)) %></p>
        <% if logged_in? %> 
          <div class="ms-4 text-center">
            <%= render "favorites/favorite_button", post: @post %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>


<div class="text-center">
  <h2 class="mt-2">User</h2>
  <div class="row">
    <div class="card col-sm-5 offset-col-3 mx-auto">
      <div class="card-header">
        <%= link_to @post.user.name, user_path(@post.user), class: "text-decoration-none" %>
      </div>
      <div class="card-body">
        <div class="row">
          <div class="col-sm-4">
            <img class="rounded me-2 mb-5 mt-4 " src="<%= gravatar_url(@post.user, {size: 100}) %>" alt="">
            <% if logged_in? %>
              <%= render "posts/follow_button",  user: @post.user %>
            <% end %>
          </div>
          <div class="col-sm-8 mt-4">
            <% if @post.user.birthday? %>
              <p class="card-text">Age:<%= (DateTime.now.to_i - @post.user.birthday.to_i)  / (86400* 365) %>
              </p>
            <% else %>
              <p class="card-text">Age: None</p>
            <% end %>
            <p class="card-text">City:<%= @post.user.city %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/top/about.html.erb
<div class="card">
  <img src="/assets/mainimg.jpg" alt="mainimg">
  <div class="card-img-overlay">
    <p class="text-white pt-2">Let's travel like a local</p>
  </div>
</div>

<div class="about text-center">
  <h1>About travelocal</h1>
  <p>〜「地元の人が暮らすように旅をする」・「地元の人との繋がりを楽しみながら旅をする」〜</p>
  <p>旅をした地で、ガイドブックに載っているお店ではなく、<br><span class="border-bottom border-3 border-dark">地元の人が行くお店で、地元の人が食べるもの</span>を、体験してほしい！という想いを込めたサイトです。</p>
  <p>・地元の方は、旅人のために、自分が普段行くお店を紹介し、活性化に繋げて欲しい！</p>
  <p>・旅をする方は、地元の方の投稿を見て、ぜひそのお店でローカルな雰囲気・文化を感じて欲しい！</p>
  <p class="text-info">地元の人々との繋がりは貴方の旅にスパイスを与えます。</p>
  
</div>  

app/views/top/index.html.erb
<div class="card">
  <img src="/assets/mainimg.jpg" alt="mainimg">
  <div class="card-img-overlay">
    <p class="text-white pt-2">Let's travel like a local</p>
  </div>
</div>

<div>
  <h1 class="text-center mt-3 pb-3 border-bottom">ALL POSTS</h1>
  <%= render "posts/index" %>
</div>

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="list-unstyled users_index">
    <% users.each do |user| %>
      <li class="mb-3 mx-auto">
        <img class="rounded me-2" src="<%= gravatar_url(user, { size: 64 }) %>" alt="">
        <div>
          <div>
            <%= user.name %>
          </div>
          <div>
            <p><%= link_to 'View profile', user_path(user), class: "text-decoration-none" %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%== pagy_bootstrap_nav(@pagy) %>
<% end %>

app/views/users/edit.html.erb
<div class="text-center">
  <h1>Edit your information</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">
    <%= form_with(model: @user) do |f| %>
      <%= render "layouts/error_message", model: f.object %>
      <div class="mb-3">
        <%= f.label :name, "Username" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= f.label :email, "Email" %>
        <%= f.email_field :email, class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= f.label :birthday, "Birthday" %>
        <%= f.date_select :birthday, use_month_numbers: true, start_year: 1900, end_year: Time.now.year - 1, prompt:"--", class:"main__box__bottom__content__group3__box__barthday__box from-control" %>
      </div>
      <div class="mb-3">
        <%= f.label :city, "City" %>
        <%= f.text_field :city, class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= f.label :password, "Password" %>
        <%= f.password_field :password, class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= f.label :password_confirmation, "Password Confirmation" %>
        <%= f.password_field :password_confirmation, class: "form-control" %>
      </div class="mb-3">
      <%= f.submit "Edit", class:"btn btn-primary w-100" %>
      </div>
    <% end %>

  </div>
</div>

app/views/users/followers.html.erb
<h1 class="text-center">Followers</h1>

<% if @followers.any? %>
 <%= render "users", users: @followers %>
<% else %>
 <p class="text-center pt-4">No Followers. <%= link_to "Let's post!", new_post_path, class:"text-decoration-none" %></p>
<% end %>

app/views/users/followings.html.erb
<h1 class="text-center">Followings</h1>

<% if @followings.any? %>
 <%= render "users", users: @followings %>
<% else %>
 <p class="text-center pt-4">No Followings. <%= link_to "Let's find someone!", root_url, class:"text-decoration-none" %></p>
<% end %>

app/views/users/likes.html.erb
<h1 class="text-center">Favorites</h1>

<%= render "posts/index" %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="card border-primary mb-3" style="max-width: 18rem;">
  <div class="card-header">採用担当の方専用</div>
  <div class="card-body text-primary">
    <p class="card-text">email: saiyou@email.com</h5>
    <p class="card-text">password: saiyou</p>
  </div>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">
    <%= form_with(model: @user) do |f| %>
      <%= render "layouts/error_message", model: f.object %>
      <div class="mb-3">
        <%= f.label :name, "Username" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= f.label :email, "Email" %>
        <%= f.email_field :email, class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= f.label :birthday, "Birthday" %>
        <%= f.date_select :birthday, use_month_numbers: true, start_year: 1900, end_year: Time.now.year - 1, prompt:"--", class:"main__box__bottom__content__group3__box__barthday__box from-control" %>
      </div>
      <div class="mb-3">
        <%= f.label :city, "City" %>
        <%= f.text_field :city, class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= f.label :password, "Password" %>
        <%= f.password_field :password, class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= f.label :password_confirmation, "Password Confirmation" %>
        <%= f.password_field :password_confirmation, class: "form-control" %>
      </div class="mb-3">
      <%= f.submit "Signup", class:"btn btn-primary w-100" %>
      </div>
    <% end %>

  </div>
</div>

app/views/users/show.html.erb
<div>
  <h2 class="text-center">Profile</h2>
  <div class="row">
    <div class="card col-sm-6 offset-col-3 mx-auto">
      <div class="card-header text-center">
        <h2><%= @user.name %></h2>
      </div>
      <div class="card-body">
        <div class="row">
          <div class="col-sm-4">
            <img class="rounded me-2 mb-5 mt-4 " src="<%= gravatar_url(@user, {size: 100}) %>" alt="">
            <% if logged_in? %>
              <%= render "posts/follow_button",  user: @user %>
            <% end %>
          </div>
          <div class="col-sm-8">
            <% if @user.birthday? %>
              <p class="card-text">Age:<%= (DateTime.now.to_i - @user.birthday.to_i)  / (86400* 365) %>
              </p>
            <% else %>
              <p class="card-text">Age: None</p>
            <% end %>
            
            <p class="card-text">City:<%= @user.city %></p>
            
            <% if current_user == @user %>
              <%= link_to "Edit", edit_user_path(@user), class: 'btn btn-outline-warning' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="mt-3">
  <h2 class="text-center">POSTS</h2>
  <%= render "posts/index" %>
</div>