config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "top#index"
  
  get 'about', to: "top#about"
  
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  
  get "signup", to: "users#new"
  resources :users, only: [:show, :create, :edit, :update, :destroy] do
    member do 
      get :followings 
      get :followers 
      get :likes
      
    end 
  end 
  
  resources :posts do
    member do 
      get :followings
    end 
  end 
  
  resources :relationships, only: [:create, :destroy]
  
  resources :favorites, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/map.rb
class Map < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  validates :name, presence:true
  belongs_to :user
  has_many :reverses_of_favorite, class_name:"Favorite", dependent: :destroy
  has_many :like_users, through: :reverses_of_favorite, source: :user, dependent: :destroy
  mount_uploader :image, ImageUploader #写真投稿用
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :name, presence: true
  validates :city, presence: true
  validates :password_digest, presence: true
  validates :email, uniqueness: { case_sensitive: false }
  
  has_many :posts, dependent: :destroy
  
  has_many :relationships, dependent: :destroy
  has_many :followings, through: :relationships, source: :follow, dependent: :destroy
  has_many :reverses_of_relationship, class_name: "Relationship", foreign_key: "follow_id", dependent: :destroy
  has_many :followers, through: :reverses_of_relationship, source: :user, dependent: :destroy
  
  has_many :favorites, dependent: :destroy
  has_many :like_posts, through: :favorites, source: :post, dependent: :destroy
  
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end 
  end 
  
  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end
  
  def following?(other_user)
    self.followings.include?(other_user)
  end 
  
  def feed_posts
    Post.where(user_id: self.following_ids)
  end 
  
  def favorite(post)
    self.favorites.find_or_create_by(post_id: post.id)
  end 
  
  def unfavorite(post)
    favorite = self.favorites.find_by(post_id: post.id)
    favorite.destroy if favorite 
  end 
  
  def favorite?(post)
    self.like_posts.include?(post)
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  include Pagy::Backend
  
  def require_user_logged_in
      unless logged_in?
          redirect_to root_url
      end 
  end 
  
  def require_current_user
    unless current_user
      redirect_to root_url
    end 
  end
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    current_user.favorite(post)
    flash[:success] = "Favorite success"
    redirect_to post_url(post)
  end

  def destroy
    post = Post.find(params[:post_id])
    current_user.unfavorite(post)
    flash[:success] = "Unfavorite success"
    redirect_to post_url(post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :require_user_logged_in, only: [:new]
  
  def index
    @posts = Post.all
  end
  
  def show
    @post = Post.find(params[:id])
  end
  
  def new
    @post = current_user.posts.build
  end 

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "Post success"
      redirect_to user_url(current_user)
    else 
      flash.now[:danger] = "Post lose"
      render :new
    end
  end
  
  def update
    if @post.update(post_params)
      flash[:success] = "Post success"
      redirect_to user_url(current_user)
    else 
      flash.now[:danger] = "Post lose"
      render :edit
    end
  end

  
  def destroy
    @post.destroy
    flash[:success] = "Delete success"
    redirect_to root_url
  end


  def followings
    @user = current_user
    @pagy,@posts = pagy(current_user.feed_posts.order(id: :desc))
  end   
  
  
  private
    def post_params
      params.require(:post).permit(:name, :genre, :comment, :station, :image, :image_cache)
    end
    
    def correct_user
      @post = current_user.posts.find_by(id: params[:id])
      unless @post 
        redirect_to root_url
      end 
    end 
    

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email,password)
      flash[:success] = "Login success"
      redirect_to followings_post_url(@user)
    else 
      flash.now[:danger] = "Login lose"
      render :new 
    end 
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "Logout success"
    redirect_to root_url
  end
  
private
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      #ログイン成功
      session[:user_id] = @user.id
      return true
    else
      #ログイン失敗
      return false
    end
  end
  
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    def index
        @pagy, @posts = pagy (Post.all)
    end 
    
    def about
    end 
    

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :followings, :followers, :likes]
  before_action :correct_user, only:[:edit, :update]
  
  def show
    @pagy, @posts = pagy(@user.posts)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Signup success"
      redirect_to root_url
    else 
      flash.now[:danger] = "signup lose"
      render :new
    end 
  end
  
  def edit 
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Update success"
      redirect_to user_url(@user)
    else 
      flash.now[:danger] = "Update lose"
      render :edit
    end
  end
  
  
  def destroy
    
  end
  
  def followings
    @user = current_user
    @pagy, @followings = pagy(@user.followings)
  end

  def followers
    @pagy, @followers = pagy(@user.followers)
  end
  
  def likes 
    @pagy, @posts = pagy(@user.like_posts)
  end
  
private
  def user_params
    params.require(:user).permit(:name, :email,:password, :password_confirmation, :birthday, :city)
  end 
  
  def set_user
    @user = User.find(params[:id])
  end 
  
  def correct_user
   @user = User.find(params[:id])
   redirect_to root_url unless @user == current_user
  end 
  
end

app/helpers/application_helper.rb
module ApplicationHelper
    include SessionsHelper
    include UsersHelper
    
    include Pagy::Frontend
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end 
  
  def logged_in?
    !!current_user 
  end 
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    end
end

app/views/layouts/_error_message.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="container-fluid bg-light">
  <footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item"><%= link_to "Travelocalについて", about_path, class:"text-muted" %></li>
    </ul>
    <p class="text-center text-muted">Travelocalは”暮らすように旅する”をコンセプトに、<br>地元の人と旅人が繋がれるサイトです。</p>
  </footer>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-sm fixed-top navbar-light bg-info">
  <div class="container-fluid ps-5 pe-5">
    <div class="mr-auto d-flex">
      <%= link_to "Travelocal", root_path, class: "navbar-brand" %><i class="mt-3 fas fa-globe-asia"></i>
    </div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"><span class="navbar-toggler-icon"></span></button>
  
    <% if logged_in? %>
      <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item"><%= link_to 'HOME', followings_post_path(current_user), class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'POST', new_post_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'FAVORITE', likes_user_path(current_user), class: 'nav-link' %></li>
          
          <li class="nav-item dropdown dropstart">
            <span class="nav-link dropdown-toggle text-decolation-none" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="far fa-user"></i>
            </span>
            <ul class="dropdown-menu text-decolation-none">
              <li class="dropdown-item"><%= link_to "My profile", user_path(current_user), class:"text-decolation-none", data: {"turbolinks"=>false} %></li>
              <li class="dropdown-item"><%= link_to "Followings", followings_user_path(current_user), class:"text-decolation-none", data: {"turbolinks"=>false} %></li>
              <li class="dropdown-item"><%= link_to "Followers", followers_user_path(current_user), class:"text-decolation-none", data: {"turbolinks"=>false} %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to "Logout", logout_path, method: :delete, class:"text-decolation-none", data: {"turbolinks"=>false} %></li>
            </ul>
          </li>
        </ul>
      </div>
      
    <% else %>
      <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "Signup", signup_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", login_path, class: "nav-link" %>
          </li>
        </ul>
      </div>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>Travelocal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <!--FontAwesome-->
    <link rel=" stylesheet " href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
    <!--Bootstrap-->
    <link rel=" stylesheet"  href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
  </head>
  <body style="padding-top: 5rem">
    <%= render "layouts/navbar" %>
    <div class="container-fluid">
      <%= render "layouts/flash_message" %>
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
  </body>
  
</html>